// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pattern.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SM.Service.Messages {

  /// <summary>Holder for reflection information generated from Pattern.proto</summary>
  public static partial class PatternReflection {

    #region Descriptor
    /// <summary>File descriptor for Pattern.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PatternReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1QYXR0ZXJuLnByb3RvEgdwYXR0ZXJuIsgCCgdQYXR0ZXJuEgoKAmlkGAEg",
            "ASgJEhsKBGluZm8YAiABKAsyDS5wYXR0ZXJuLkluZm8SHwoGY2FudmFzGAMg",
            "ASgLMg8ucGF0dGVybi5DYW52YXMSLAoNc3RyYW5kc19jb3VudBgEIAEoCzIV",
            "LnBhdHRlcm4uU3RyYW5kc0NvdW50Eg0KBXdpZHRoGAUgASgNEg4KBmhlaWdo",
            "dBgGIAEoDRI0Cg5jb25maWd1cmF0aW9ucxgHIAMoCzIcLnBhdHRlcm4uU3Rp",
            "dGNoQ29uZmlndXJhdGlvbhIhCghzdGl0Y2hlcxgIIAMoCzIPLnBhdHRlcm4u",
            "U3RpdGNoEikKDGJhY2tzdGl0Y2hlcxgJIAMoCzITLnBhdHRlcm4uQmFja3N0",
            "aXRjaBIiCghlbGVtZW50cxgKIAMoCzIQLnBhdHRlcm4uRWxlbWVudCJJCgRJ",
            "bmZvEg0KBXRpdGxlGAEgASgJEg4KBmF1dGhvchgCIAEoCRIPCgdjb21wYW55",
            "GAMgASgJEhEKCWNvcHlyaWdodBgEIAEoCSIXCgZDYW52YXMSDQoFdGl0bGUY",
            "ASABKAkiigEKDFN0cmFuZHNDb3VudBIMCgRmdWxsGAEgASgFEgwKBGhhbGYY",
            "AiABKAUSDwoHcXVhcnRlchgDIAEoBRIVCg10aHJlZV9xdWFydGVyGAQgASgF",
            "Eg0KBXBldGl0GAUgASgFEhIKCmJhY2tzdGl0Y2gYBiABKAUSEwoLZnJlbmNo",
            "X2tub3QYByABKAUiOAoTU3RpdGNoQ29uZmlndXJhdGlvbhIOCgZzeW1ib2wY",
            "ASABKAkSEQoJaGV4X2NvbG9yGAIgASgJImcKBlN0aXRjaBIdCgVwb2ludBgB",
            "IAEoCzIOLnBhdHRlcm4uUG9pbnQSIQoEdHlwZRgCIAEoDjITLnBhdHRlcm4u",
            "U3RpdGNoVHlwZRIbChNjb25maWd1cmF0aW9uX2luZGV4GAMgASgFIh0KBVBv",
            "aW50EgkKAVgYASABKAMSCQoBWRgCIAEoAyJxCgpCYWNrc3RpdGNoEiMKC3N0",
            "YXJ0X3BvaW50GAEgASgLMg4ucGF0dGVybi5Qb2ludBIhCgllbmRfcG9pbnQY",
            "AiABKAsyDi5wYXR0ZXJuLlBvaW50EhsKE2NvbmZpZ3VyYXRpb25faW5kZXgY",
            "AyABKAUiaQoHRWxlbWVudBIdCgVwb2ludBgBIAEoCzIOLnBhdHRlcm4uUG9p",
            "bnQSGwoTY29uZmlndXJhdGlvbl9pbmRleBgCIAEoBRIiCgR0eXBlGAMgASgO",
            "MhQucGF0dGVybi5FbGVtZW50VHlwZSpUCgpTdGl0Y2hUeXBlEggKBE5PTkUQ",
            "ABIICgRGVUxMEAESCAoESEFMRhACEgsKB1FVQVJURVIQAxIQCgxUSFJFRVFV",
            "QVJURVIQBBIJCgVQRVRJVBAFKjYKC0VsZW1lbnRUeXBlEg0KCVVOREVGSU5F",
            "RBAAEg4KCkZSRU5DSEtOT1QQARIICgRCRUFEEAJCFqoCE1NNLlNlcnZpY2Uu",
            "TWVzc2FnZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SM.Service.Messages.StitchType), typeof(global::SM.Service.Messages.ElementType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Pattern), global::SM.Service.Messages.Pattern.Parser, new[]{ "Id", "Info", "Canvas", "StrandsCount", "Width", "Height", "Configurations", "Stitches", "Backstitches", "Elements" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Info), global::SM.Service.Messages.Info.Parser, new[]{ "Title", "Author", "Company", "Copyright" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Canvas), global::SM.Service.Messages.Canvas.Parser, new[]{ "Title" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.StrandsCount), global::SM.Service.Messages.StrandsCount.Parser, new[]{ "Full", "Half", "Quarter", "ThreeQuarter", "Petit", "Backstitch", "FrenchKnot" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.StitchConfiguration), global::SM.Service.Messages.StitchConfiguration.Parser, new[]{ "Symbol", "HexColor" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Stitch), global::SM.Service.Messages.Stitch.Parser, new[]{ "Point", "Type", "ConfigurationIndex" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Point), global::SM.Service.Messages.Point.Parser, new[]{ "X", "Y" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Backstitch), global::SM.Service.Messages.Backstitch.Parser, new[]{ "StartPoint", "EndPoint", "ConfigurationIndex" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SM.Service.Messages.Element), global::SM.Service.Messages.Element.Parser, new[]{ "Point", "ConfigurationIndex", "Type" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum StitchType {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("FULL")] Full = 1,
    [pbr::OriginalName("HALF")] Half = 2,
    [pbr::OriginalName("QUARTER")] Quarter = 3,
    [pbr::OriginalName("THREEQUARTER")] Threequarter = 4,
    [pbr::OriginalName("PETIT")] Petit = 5,
  }

  public enum ElementType {
    [pbr::OriginalName("UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("FRENCHKNOT")] Frenchknot = 1,
    [pbr::OriginalName("BEAD")] Bead = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Pattern : pb::IMessage<Pattern> {
    private static readonly pb::MessageParser<Pattern> _parser = new pb::MessageParser<Pattern>(() => new Pattern());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Pattern> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pattern() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pattern(Pattern other) : this() {
      id_ = other.id_;
      Info = other.info_ != null ? other.Info.Clone() : null;
      Canvas = other.canvas_ != null ? other.Canvas.Clone() : null;
      StrandsCount = other.strandsCount_ != null ? other.StrandsCount.Clone() : null;
      width_ = other.width_;
      height_ = other.height_;
      configurations_ = other.configurations_.Clone();
      stitches_ = other.stitches_.Clone();
      backstitches_ = other.backstitches_.Clone();
      elements_ = other.elements_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pattern Clone() {
      return new Pattern(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 2;
    private global::SM.Service.Messages.Info info_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Info Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "canvas" field.</summary>
    public const int CanvasFieldNumber = 3;
    private global::SM.Service.Messages.Canvas canvas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Canvas Canvas {
      get { return canvas_; }
      set {
        canvas_ = value;
      }
    }

    /// <summary>Field number for the "strands_count" field.</summary>
    public const int StrandsCountFieldNumber = 4;
    private global::SM.Service.Messages.StrandsCount strandsCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.StrandsCount StrandsCount {
      get { return strandsCount_; }
      set {
        strandsCount_ = value;
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 5;
    private uint width_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 6;
    private uint height_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "configurations" field.</summary>
    public const int ConfigurationsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::SM.Service.Messages.StitchConfiguration> _repeated_configurations_codec
        = pb::FieldCodec.ForMessage(58, global::SM.Service.Messages.StitchConfiguration.Parser);
    private readonly pbc::RepeatedField<global::SM.Service.Messages.StitchConfiguration> configurations_ = new pbc::RepeatedField<global::SM.Service.Messages.StitchConfiguration>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SM.Service.Messages.StitchConfiguration> Configurations {
      get { return configurations_; }
    }

    /// <summary>Field number for the "stitches" field.</summary>
    public const int StitchesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::SM.Service.Messages.Stitch> _repeated_stitches_codec
        = pb::FieldCodec.ForMessage(66, global::SM.Service.Messages.Stitch.Parser);
    private readonly pbc::RepeatedField<global::SM.Service.Messages.Stitch> stitches_ = new pbc::RepeatedField<global::SM.Service.Messages.Stitch>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SM.Service.Messages.Stitch> Stitches {
      get { return stitches_; }
    }

    /// <summary>Field number for the "backstitches" field.</summary>
    public const int BackstitchesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::SM.Service.Messages.Backstitch> _repeated_backstitches_codec
        = pb::FieldCodec.ForMessage(74, global::SM.Service.Messages.Backstitch.Parser);
    private readonly pbc::RepeatedField<global::SM.Service.Messages.Backstitch> backstitches_ = new pbc::RepeatedField<global::SM.Service.Messages.Backstitch>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SM.Service.Messages.Backstitch> Backstitches {
      get { return backstitches_; }
    }

    /// <summary>Field number for the "elements" field.</summary>
    public const int ElementsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::SM.Service.Messages.Element> _repeated_elements_codec
        = pb::FieldCodec.ForMessage(82, global::SM.Service.Messages.Element.Parser);
    private readonly pbc::RepeatedField<global::SM.Service.Messages.Element> elements_ = new pbc::RepeatedField<global::SM.Service.Messages.Element>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SM.Service.Messages.Element> Elements {
      get { return elements_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Pattern);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Pattern other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Info, other.Info)) return false;
      if (!object.Equals(Canvas, other.Canvas)) return false;
      if (!object.Equals(StrandsCount, other.StrandsCount)) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if(!configurations_.Equals(other.configurations_)) return false;
      if(!stitches_.Equals(other.stitches_)) return false;
      if(!backstitches_.Equals(other.backstitches_)) return false;
      if(!elements_.Equals(other.elements_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      if (canvas_ != null) hash ^= Canvas.GetHashCode();
      if (strandsCount_ != null) hash ^= StrandsCount.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      hash ^= configurations_.GetHashCode();
      hash ^= stitches_.GetHashCode();
      hash ^= backstitches_.GetHashCode();
      hash ^= elements_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (canvas_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Canvas);
      }
      if (strandsCount_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StrandsCount);
      }
      if (Width != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Height);
      }
      configurations_.WriteTo(output, _repeated_configurations_codec);
      stitches_.WriteTo(output, _repeated_stitches_codec);
      backstitches_.WriteTo(output, _repeated_backstitches_codec);
      elements_.WriteTo(output, _repeated_elements_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (canvas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Canvas);
      }
      if (strandsCount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StrandsCount);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Height);
      }
      size += configurations_.CalculateSize(_repeated_configurations_codec);
      size += stitches_.CalculateSize(_repeated_stitches_codec);
      size += backstitches_.CalculateSize(_repeated_backstitches_codec);
      size += elements_.CalculateSize(_repeated_elements_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Pattern other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          info_ = new global::SM.Service.Messages.Info();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.canvas_ != null) {
        if (canvas_ == null) {
          canvas_ = new global::SM.Service.Messages.Canvas();
        }
        Canvas.MergeFrom(other.Canvas);
      }
      if (other.strandsCount_ != null) {
        if (strandsCount_ == null) {
          strandsCount_ = new global::SM.Service.Messages.StrandsCount();
        }
        StrandsCount.MergeFrom(other.StrandsCount);
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      configurations_.Add(other.configurations_);
      stitches_.Add(other.stitches_);
      backstitches_.Add(other.backstitches_);
      elements_.Add(other.elements_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (info_ == null) {
              info_ = new global::SM.Service.Messages.Info();
            }
            input.ReadMessage(info_);
            break;
          }
          case 26: {
            if (canvas_ == null) {
              canvas_ = new global::SM.Service.Messages.Canvas();
            }
            input.ReadMessage(canvas_);
            break;
          }
          case 34: {
            if (strandsCount_ == null) {
              strandsCount_ = new global::SM.Service.Messages.StrandsCount();
            }
            input.ReadMessage(strandsCount_);
            break;
          }
          case 40: {
            Width = input.ReadUInt32();
            break;
          }
          case 48: {
            Height = input.ReadUInt32();
            break;
          }
          case 58: {
            configurations_.AddEntriesFrom(input, _repeated_configurations_codec);
            break;
          }
          case 66: {
            stitches_.AddEntriesFrom(input, _repeated_stitches_codec);
            break;
          }
          case 74: {
            backstitches_.AddEntriesFrom(input, _repeated_backstitches_codec);
            break;
          }
          case 82: {
            elements_.AddEntriesFrom(input, _repeated_elements_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Info : pb::IMessage<Info> {
    private static readonly pb::MessageParser<Info> _parser = new pb::MessageParser<Info>(() => new Info());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Info> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Info() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Info(Info other) : this() {
      title_ = other.title_;
      author_ = other.author_;
      company_ = other.company_;
      copyright_ = other.copyright_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Info Clone() {
      return new Info(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "author" field.</summary>
    public const int AuthorFieldNumber = 2;
    private string author_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Author {
      get { return author_; }
      set {
        author_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "company" field.</summary>
    public const int CompanyFieldNumber = 3;
    private string company_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Company {
      get { return company_; }
      set {
        company_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "copyright" field.</summary>
    public const int CopyrightFieldNumber = 4;
    private string copyright_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Copyright {
      get { return copyright_; }
      set {
        copyright_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Info);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Info other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if (Author != other.Author) return false;
      if (Company != other.Company) return false;
      if (Copyright != other.Copyright) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Author.Length != 0) hash ^= Author.GetHashCode();
      if (Company.Length != 0) hash ^= Company.GetHashCode();
      if (Copyright.Length != 0) hash ^= Copyright.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Author.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Author);
      }
      if (Company.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Company);
      }
      if (Copyright.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Copyright);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Author.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Author);
      }
      if (Company.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Company);
      }
      if (Copyright.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Copyright);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Info other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Author.Length != 0) {
        Author = other.Author;
      }
      if (other.Company.Length != 0) {
        Company = other.Company;
      }
      if (other.Copyright.Length != 0) {
        Copyright = other.Copyright;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Author = input.ReadString();
            break;
          }
          case 26: {
            Company = input.ReadString();
            break;
          }
          case 34: {
            Copyright = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Canvas : pb::IMessage<Canvas> {
    private static readonly pb::MessageParser<Canvas> _parser = new pb::MessageParser<Canvas>(() => new Canvas());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Canvas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Canvas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Canvas(Canvas other) : this() {
      title_ = other.title_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Canvas Clone() {
      return new Canvas(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Canvas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Canvas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Canvas other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StrandsCount : pb::IMessage<StrandsCount> {
    private static readonly pb::MessageParser<StrandsCount> _parser = new pb::MessageParser<StrandsCount>(() => new StrandsCount());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StrandsCount> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StrandsCount() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StrandsCount(StrandsCount other) : this() {
      full_ = other.full_;
      half_ = other.half_;
      quarter_ = other.quarter_;
      threeQuarter_ = other.threeQuarter_;
      petit_ = other.petit_;
      backstitch_ = other.backstitch_;
      frenchKnot_ = other.frenchKnot_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StrandsCount Clone() {
      return new StrandsCount(this);
    }

    /// <summary>Field number for the "full" field.</summary>
    public const int FullFieldNumber = 1;
    private int full_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Full {
      get { return full_; }
      set {
        full_ = value;
      }
    }

    /// <summary>Field number for the "half" field.</summary>
    public const int HalfFieldNumber = 2;
    private int half_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Half {
      get { return half_; }
      set {
        half_ = value;
      }
    }

    /// <summary>Field number for the "quarter" field.</summary>
    public const int QuarterFieldNumber = 3;
    private int quarter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quarter {
      get { return quarter_; }
      set {
        quarter_ = value;
      }
    }

    /// <summary>Field number for the "three_quarter" field.</summary>
    public const int ThreeQuarterFieldNumber = 4;
    private int threeQuarter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ThreeQuarter {
      get { return threeQuarter_; }
      set {
        threeQuarter_ = value;
      }
    }

    /// <summary>Field number for the "petit" field.</summary>
    public const int PetitFieldNumber = 5;
    private int petit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Petit {
      get { return petit_; }
      set {
        petit_ = value;
      }
    }

    /// <summary>Field number for the "backstitch" field.</summary>
    public const int BackstitchFieldNumber = 6;
    private int backstitch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Backstitch {
      get { return backstitch_; }
      set {
        backstitch_ = value;
      }
    }

    /// <summary>Field number for the "french_knot" field.</summary>
    public const int FrenchKnotFieldNumber = 7;
    private int frenchKnot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FrenchKnot {
      get { return frenchKnot_; }
      set {
        frenchKnot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StrandsCount);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StrandsCount other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Full != other.Full) return false;
      if (Half != other.Half) return false;
      if (Quarter != other.Quarter) return false;
      if (ThreeQuarter != other.ThreeQuarter) return false;
      if (Petit != other.Petit) return false;
      if (Backstitch != other.Backstitch) return false;
      if (FrenchKnot != other.FrenchKnot) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Full != 0) hash ^= Full.GetHashCode();
      if (Half != 0) hash ^= Half.GetHashCode();
      if (Quarter != 0) hash ^= Quarter.GetHashCode();
      if (ThreeQuarter != 0) hash ^= ThreeQuarter.GetHashCode();
      if (Petit != 0) hash ^= Petit.GetHashCode();
      if (Backstitch != 0) hash ^= Backstitch.GetHashCode();
      if (FrenchKnot != 0) hash ^= FrenchKnot.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Full != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Full);
      }
      if (Half != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Half);
      }
      if (Quarter != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Quarter);
      }
      if (ThreeQuarter != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ThreeQuarter);
      }
      if (Petit != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Petit);
      }
      if (Backstitch != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Backstitch);
      }
      if (FrenchKnot != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(FrenchKnot);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Full != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Full);
      }
      if (Half != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Half);
      }
      if (Quarter != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quarter);
      }
      if (ThreeQuarter != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ThreeQuarter);
      }
      if (Petit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Petit);
      }
      if (Backstitch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Backstitch);
      }
      if (FrenchKnot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrenchKnot);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StrandsCount other) {
      if (other == null) {
        return;
      }
      if (other.Full != 0) {
        Full = other.Full;
      }
      if (other.Half != 0) {
        Half = other.Half;
      }
      if (other.Quarter != 0) {
        Quarter = other.Quarter;
      }
      if (other.ThreeQuarter != 0) {
        ThreeQuarter = other.ThreeQuarter;
      }
      if (other.Petit != 0) {
        Petit = other.Petit;
      }
      if (other.Backstitch != 0) {
        Backstitch = other.Backstitch;
      }
      if (other.FrenchKnot != 0) {
        FrenchKnot = other.FrenchKnot;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Full = input.ReadInt32();
            break;
          }
          case 16: {
            Half = input.ReadInt32();
            break;
          }
          case 24: {
            Quarter = input.ReadInt32();
            break;
          }
          case 32: {
            ThreeQuarter = input.ReadInt32();
            break;
          }
          case 40: {
            Petit = input.ReadInt32();
            break;
          }
          case 48: {
            Backstitch = input.ReadInt32();
            break;
          }
          case 56: {
            FrenchKnot = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StitchConfiguration : pb::IMessage<StitchConfiguration> {
    private static readonly pb::MessageParser<StitchConfiguration> _parser = new pb::MessageParser<StitchConfiguration>(() => new StitchConfiguration());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StitchConfiguration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StitchConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StitchConfiguration(StitchConfiguration other) : this() {
      symbol_ = other.symbol_;
      hexColor_ = other.hexColor_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StitchConfiguration Clone() {
      return new StitchConfiguration(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hex_color" field.</summary>
    public const int HexColorFieldNumber = 2;
    private string hexColor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HexColor {
      get { return hexColor_; }
      set {
        hexColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StitchConfiguration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StitchConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if (HexColor != other.HexColor) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (HexColor.Length != 0) hash ^= HexColor.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      if (HexColor.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HexColor);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (HexColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HexColor);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StitchConfiguration other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      if (other.HexColor.Length != 0) {
        HexColor = other.HexColor;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            HexColor = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Stitch : pb::IMessage<Stitch> {
    private static readonly pb::MessageParser<Stitch> _parser = new pb::MessageParser<Stitch>(() => new Stitch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Stitch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stitch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stitch(Stitch other) : this() {
      Point = other.point_ != null ? other.Point.Clone() : null;
      type_ = other.type_;
      configurationIndex_ = other.configurationIndex_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stitch Clone() {
      return new Stitch(this);
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 1;
    private global::SM.Service.Messages.Point point_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Point Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::SM.Service.Messages.StitchType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.StitchType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "configuration_index" field.</summary>
    public const int ConfigurationIndexFieldNumber = 3;
    private int configurationIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfigurationIndex {
      get { return configurationIndex_; }
      set {
        configurationIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Stitch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Stitch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Point, other.Point)) return false;
      if (Type != other.Type) return false;
      if (ConfigurationIndex != other.ConfigurationIndex) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (point_ != null) hash ^= Point.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ConfigurationIndex != 0) hash ^= ConfigurationIndex.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (point_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Point);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (ConfigurationIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ConfigurationIndex);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (point_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Point);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (ConfigurationIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfigurationIndex);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Stitch other) {
      if (other == null) {
        return;
      }
      if (other.point_ != null) {
        if (point_ == null) {
          point_ = new global::SM.Service.Messages.Point();
        }
        Point.MergeFrom(other.Point);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ConfigurationIndex != 0) {
        ConfigurationIndex = other.ConfigurationIndex;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (point_ == null) {
              point_ = new global::SM.Service.Messages.Point();
            }
            input.ReadMessage(point_);
            break;
          }
          case 16: {
            type_ = (global::SM.Service.Messages.StitchType) input.ReadEnum();
            break;
          }
          case 24: {
            ConfigurationIndex = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Point : pb::IMessage<Point> {
    private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Point> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point(Point other) : this() {
      x_ = other.x_;
      y_ = other.y_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point Clone() {
      return new Point(this);
    }

    /// <summary>Field number for the "X" field.</summary>
    public const int XFieldNumber = 1;
    private long x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "Y" field.</summary>
    public const int YFieldNumber = 2;
    private long y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Point);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Point other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0L) hash ^= X.GetHashCode();
      if (Y != 0L) hash ^= Y.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(X);
      }
      if (Y != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Y);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(X);
      }
      if (Y != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Y);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Point other) {
      if (other == null) {
        return;
      }
      if (other.X != 0L) {
        X = other.X;
      }
      if (other.Y != 0L) {
        Y = other.Y;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            X = input.ReadInt64();
            break;
          }
          case 16: {
            Y = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Backstitch : pb::IMessage<Backstitch> {
    private static readonly pb::MessageParser<Backstitch> _parser = new pb::MessageParser<Backstitch>(() => new Backstitch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Backstitch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Backstitch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Backstitch(Backstitch other) : this() {
      StartPoint = other.startPoint_ != null ? other.StartPoint.Clone() : null;
      EndPoint = other.endPoint_ != null ? other.EndPoint.Clone() : null;
      configurationIndex_ = other.configurationIndex_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Backstitch Clone() {
      return new Backstitch(this);
    }

    /// <summary>Field number for the "start_point" field.</summary>
    public const int StartPointFieldNumber = 1;
    private global::SM.Service.Messages.Point startPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Point StartPoint {
      get { return startPoint_; }
      set {
        startPoint_ = value;
      }
    }

    /// <summary>Field number for the "end_point" field.</summary>
    public const int EndPointFieldNumber = 2;
    private global::SM.Service.Messages.Point endPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Point EndPoint {
      get { return endPoint_; }
      set {
        endPoint_ = value;
      }
    }

    /// <summary>Field number for the "configuration_index" field.</summary>
    public const int ConfigurationIndexFieldNumber = 3;
    private int configurationIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfigurationIndex {
      get { return configurationIndex_; }
      set {
        configurationIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Backstitch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Backstitch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartPoint, other.StartPoint)) return false;
      if (!object.Equals(EndPoint, other.EndPoint)) return false;
      if (ConfigurationIndex != other.ConfigurationIndex) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startPoint_ != null) hash ^= StartPoint.GetHashCode();
      if (endPoint_ != null) hash ^= EndPoint.GetHashCode();
      if (ConfigurationIndex != 0) hash ^= ConfigurationIndex.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startPoint_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(StartPoint);
      }
      if (endPoint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EndPoint);
      }
      if (ConfigurationIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ConfigurationIndex);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartPoint);
      }
      if (endPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndPoint);
      }
      if (ConfigurationIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfigurationIndex);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Backstitch other) {
      if (other == null) {
        return;
      }
      if (other.startPoint_ != null) {
        if (startPoint_ == null) {
          startPoint_ = new global::SM.Service.Messages.Point();
        }
        StartPoint.MergeFrom(other.StartPoint);
      }
      if (other.endPoint_ != null) {
        if (endPoint_ == null) {
          endPoint_ = new global::SM.Service.Messages.Point();
        }
        EndPoint.MergeFrom(other.EndPoint);
      }
      if (other.ConfigurationIndex != 0) {
        ConfigurationIndex = other.ConfigurationIndex;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (startPoint_ == null) {
              startPoint_ = new global::SM.Service.Messages.Point();
            }
            input.ReadMessage(startPoint_);
            break;
          }
          case 18: {
            if (endPoint_ == null) {
              endPoint_ = new global::SM.Service.Messages.Point();
            }
            input.ReadMessage(endPoint_);
            break;
          }
          case 24: {
            ConfigurationIndex = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Element : pb::IMessage<Element> {
    private static readonly pb::MessageParser<Element> _parser = new pb::MessageParser<Element>(() => new Element());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Element> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SM.Service.Messages.PatternReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Element() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Element(Element other) : this() {
      Point = other.point_ != null ? other.Point.Clone() : null;
      configurationIndex_ = other.configurationIndex_;
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Element Clone() {
      return new Element(this);
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 1;
    private global::SM.Service.Messages.Point point_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.Point Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "configuration_index" field.</summary>
    public const int ConfigurationIndexFieldNumber = 2;
    private int configurationIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConfigurationIndex {
      get { return configurationIndex_; }
      set {
        configurationIndex_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::SM.Service.Messages.ElementType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SM.Service.Messages.ElementType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Element);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Element other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Point, other.Point)) return false;
      if (ConfigurationIndex != other.ConfigurationIndex) return false;
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (point_ != null) hash ^= Point.GetHashCode();
      if (ConfigurationIndex != 0) hash ^= ConfigurationIndex.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (point_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Point);
      }
      if (ConfigurationIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ConfigurationIndex);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (point_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Point);
      }
      if (ConfigurationIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConfigurationIndex);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Element other) {
      if (other == null) {
        return;
      }
      if (other.point_ != null) {
        if (point_ == null) {
          point_ = new global::SM.Service.Messages.Point();
        }
        Point.MergeFrom(other.Point);
      }
      if (other.ConfigurationIndex != 0) {
        ConfigurationIndex = other.ConfigurationIndex;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (point_ == null) {
              point_ = new global::SM.Service.Messages.Point();
            }
            input.ReadMessage(point_);
            break;
          }
          case 16: {
            ConfigurationIndex = input.ReadInt32();
            break;
          }
          case 24: {
            type_ = (global::SM.Service.Messages.ElementType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
